name: Build Unity Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build GameBelka
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4    # Обновили до v4

      - name: Cache Library
        uses: actions/cache@v3       # Обновили до v3
        with:
          path: Library
          key: Library-GameBelka
          restore-keys: Library-GameBelka-

      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          allowDirtyBuild: true

      - name: Upload build
        uses: actions/upload-artifact@v4    # Обновили до v4
        with:
          name: GameBelka-Build
          path: build